name: ParaToGit

on:
  schedule:
    - cron:  '0 4,16 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: CheckUpdate
      id: check_update
      run: |
        $response = Invoke-WebRequest -Uri https://paratranz.cn/api/projects/6860 -Method Get
        $content = $response.Content | ConvertFrom-Json
        if ($content.stats.tp -eq 1) {
            echo "has_updater=true" >> $env:GITHUB_OUTPUT
        } else {
            echo "no updater"
        }
#    - name: Checkout
#      uses: actions/checkout@v3
#      with:
#        repository: 'LocalizeLimbusCompany/LocalizeLimbusCompany'
#        path: LocalizeLimbusCompany
    - name: Run build script
      if: steps.check_update.outputs.has_update == 'true'
      id: check_error
      run: |
        ./Download.ps1 ${{ secrets.PARATRANZ_ROOT }}
    - name: Upload Error.txt to artifact
      if: steps.check_error.outputs.has_error == 'true'
      uses: actions/upload-artifact@v2
      with:
        name: error-log
        path: ./Error.txt
    - name: Cancel workflow if Error.txt exists
      if: steps.check_error.outputs.has_error == 'true'
      run: |
        echo "Error detected, cancelling workflow"
        echo ${{  steps.check_error.outputs.error  }}
        exit 1
