name: ParaToGit

on:
  schedule:
    - cron:  '0 4,16 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
         repository: 'LocalizeLimbusCompany/LocalizeLimbusCompany'
         path: LocalizeLimbusCompany
         token: ${{ secrets.ROOT }}
    - name: Checkout
      uses: actions/checkout@v3
      with:
         path: LocalizeLimbusCompany/Localize
    - name: Run build script
      id: check_error
      run: |
        ./LocalizeLimbusCompany/Localize/Download.ps1 ${{ secrets.PARATRANZ_ROOT }}
    - name: Upload Error.txt to artifact
      if: steps.check_error.outputs.has_error == 'true'
      uses: actions/upload-artifact@v2
      with:
        name: error-log
        path: ./LocalizeLimbusCompany/Localize/Error.txt
    - name: Cancel workflow if Error.txt exists
      if: steps.check_error.outputs.has_error == 'true'
      run: |
        echo "Error detected, cancelling workflow"
        echo ${{  steps.check_error.outputs.error  }}
        exit 1
    - name: Upload BIE Full
      uses: actions/upload-artifact@v3
      with:
        name: LimbusLocalize_BIE_Dev.7z
        path: LocalizeLimbusCompany/Release/LimbusLocalize_BIE_Dev.7z